// <auto-generated />
using System;
using CinemaCity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaCity.Data.Migrations
{
    [DbContext(typeof(CinemaCityContext))]
    [Migration("20240528090307_ChangeBTColumnName")]
    partial class ChangeBTColumnName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaCity.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2024, 5, 28, 11, 36, 12, 0, DateTimeKind.Unspecified),
                            ShowtimeId = 1,
                            UserId = "acc2665f-25bd-43f8-87e5-6027c253b3cc"
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2024, 5, 28, 11, 40, 12, 0, DateTimeKind.Unspecified),
                            ShowtimeId = 1,
                            UserId = "acc2665f-25bd-43f8-87e5-6027c253b3cc"
                        });
                });

            modelBuilder.Entity("CinemaCity.Data.Models.BookingSeat", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "SeatId");

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("BookingSeats");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.BookingTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("BookingTickets");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaName = "Cinema City - Sofia",
                            Location = "The Mall Sofia"
                        },
                        new
                        {
                            Id = 2,
                            CinemaName = "Cinema City - Varna",
                            Location = "Grand Mall Varna"
                        },
                        new
                        {
                            Id = 3,
                            CinemaName = "Cinema City - Ruse",
                            Location = "Mall Ruse"
                        });
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subtitles")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Audio = "EN",
                            Category = "C",
                            Description = "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
                            Duration = 150,
                            GenreId = 6,
                            Rating = 7.2999999999999998,
                            ReleaseDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "BG",
                            Title = "Kingdom of the Planet of the Apes"
                        },
                        new
                        {
                            Id = 2,
                            Audio = "EN",
                            Category = "C",
                            Description = "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.",
                            Duration = 126,
                            GenreId = 1,
                            Rating = 7.2999999999999998,
                            ReleaseDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "BG",
                            Title = "The Fall Guy"
                        },
                        new
                        {
                            Id = 3,
                            Audio = "EN",
                            Category = "C+",
                            Description = "Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a 'Challenger' event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi's former boyfriend.",
                            Duration = 131,
                            GenreId = 2,
                            Rating = 7.5999999999999996,
                            ReleaseDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "BG",
                            Title = "Challengers"
                        },
                        new
                        {
                            Id = 4,
                            Audio = "EN",
                            Category = "D",
                            Description = "A journey across a dystopian future America, following a team of military-embedded journalists as they race against time to reach DC before rebel factions descend upon the White House.",
                            Duration = 110,
                            GenreId = 1,
                            Rating = 7.5,
                            ReleaseDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "BG",
                            Title = "Civil War"
                        },
                        new
                        {
                            Id = 5,
                            Audio = "EN",
                            Category = "D",
                            Description = "Kid, an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
                            Duration = 122,
                            GenreId = 7,
                            Rating = 7.0,
                            ReleaseDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "BG",
                            Title = "Monkey Man"
                        });
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            ColumnNumber = 1,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            ColumnNumber = 2,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 1,
                            ColumnNumber = 3,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 1,
                            ColumnNumber = 4,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 1,
                            ColumnNumber = 5,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 1,
                            ColumnNumber = 6,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 7,
                            CinemaId = 1,
                            ColumnNumber = 7,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            CinemaId = 1,
                            ColumnNumber = 8,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 9,
                            CinemaId = 1,
                            ColumnNumber = 9,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 10,
                            CinemaId = 1,
                            ColumnNumber = 10,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 11,
                            CinemaId = 1,
                            ColumnNumber = 1,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 12,
                            CinemaId = 1,
                            ColumnNumber = 2,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 13,
                            CinemaId = 1,
                            ColumnNumber = 3,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 14,
                            CinemaId = 1,
                            ColumnNumber = 4,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 15,
                            CinemaId = 1,
                            ColumnNumber = 5,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 16,
                            CinemaId = 1,
                            ColumnNumber = 6,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 17,
                            CinemaId = 1,
                            ColumnNumber = 7,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 18,
                            CinemaId = 1,
                            ColumnNumber = 8,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 19,
                            CinemaId = 1,
                            ColumnNumber = 9,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 20,
                            CinemaId = 1,
                            ColumnNumber = 10,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 21,
                            CinemaId = 1,
                            ColumnNumber = 1,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 22,
                            CinemaId = 1,
                            ColumnNumber = 2,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 23,
                            CinemaId = 1,
                            ColumnNumber = 3,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 24,
                            CinemaId = 1,
                            ColumnNumber = 4,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 25,
                            CinemaId = 1,
                            ColumnNumber = 5,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 26,
                            CinemaId = 1,
                            ColumnNumber = 6,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 27,
                            CinemaId = 1,
                            ColumnNumber = 7,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 28,
                            CinemaId = 1,
                            ColumnNumber = 8,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 29,
                            CinemaId = 1,
                            ColumnNumber = 9,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 30,
                            CinemaId = 1,
                            ColumnNumber = 10,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 31,
                            CinemaId = 1,
                            ColumnNumber = 1,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 32,
                            CinemaId = 1,
                            ColumnNumber = 2,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 33,
                            CinemaId = 1,
                            ColumnNumber = 3,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 34,
                            CinemaId = 1,
                            ColumnNumber = 4,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 35,
                            CinemaId = 1,
                            ColumnNumber = 5,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 36,
                            CinemaId = 1,
                            ColumnNumber = 6,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 37,
                            CinemaId = 1,
                            ColumnNumber = 7,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 38,
                            CinemaId = 1,
                            ColumnNumber = 8,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 39,
                            CinemaId = 1,
                            ColumnNumber = 9,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 40,
                            CinemaId = 1,
                            ColumnNumber = 10,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 41,
                            CinemaId = 1,
                            ColumnNumber = 1,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 42,
                            CinemaId = 1,
                            ColumnNumber = 2,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 43,
                            CinemaId = 1,
                            ColumnNumber = 3,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 44,
                            CinemaId = 1,
                            ColumnNumber = 4,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 45,
                            CinemaId = 1,
                            ColumnNumber = 5,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 46,
                            CinemaId = 1,
                            ColumnNumber = 6,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 47,
                            CinemaId = 1,
                            ColumnNumber = 7,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 48,
                            CinemaId = 1,
                            ColumnNumber = 8,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 49,
                            CinemaId = 1,
                            ColumnNumber = 9,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 50,
                            CinemaId = 1,
                            ColumnNumber = 10,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 51,
                            CinemaId = 2,
                            ColumnNumber = 1,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 52,
                            CinemaId = 2,
                            ColumnNumber = 2,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 53,
                            CinemaId = 2,
                            ColumnNumber = 3,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 54,
                            CinemaId = 2,
                            ColumnNumber = 4,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 55,
                            CinemaId = 2,
                            ColumnNumber = 5,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 56,
                            CinemaId = 2,
                            ColumnNumber = 6,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 57,
                            CinemaId = 2,
                            ColumnNumber = 7,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 58,
                            CinemaId = 2,
                            ColumnNumber = 8,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 59,
                            CinemaId = 2,
                            ColumnNumber = 9,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 60,
                            CinemaId = 2,
                            ColumnNumber = 10,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 61,
                            CinemaId = 2,
                            ColumnNumber = 1,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 62,
                            CinemaId = 2,
                            ColumnNumber = 2,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 63,
                            CinemaId = 2,
                            ColumnNumber = 3,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 64,
                            CinemaId = 2,
                            ColumnNumber = 4,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 65,
                            CinemaId = 2,
                            ColumnNumber = 5,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 66,
                            CinemaId = 2,
                            ColumnNumber = 6,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 67,
                            CinemaId = 2,
                            ColumnNumber = 7,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 68,
                            CinemaId = 2,
                            ColumnNumber = 8,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 69,
                            CinemaId = 2,
                            ColumnNumber = 9,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 70,
                            CinemaId = 2,
                            ColumnNumber = 10,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 71,
                            CinemaId = 2,
                            ColumnNumber = 1,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 72,
                            CinemaId = 2,
                            ColumnNumber = 2,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 73,
                            CinemaId = 2,
                            ColumnNumber = 3,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 74,
                            CinemaId = 2,
                            ColumnNumber = 4,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 75,
                            CinemaId = 2,
                            ColumnNumber = 5,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 76,
                            CinemaId = 2,
                            ColumnNumber = 6,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 77,
                            CinemaId = 2,
                            ColumnNumber = 7,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 78,
                            CinemaId = 2,
                            ColumnNumber = 8,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 79,
                            CinemaId = 2,
                            ColumnNumber = 9,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 80,
                            CinemaId = 2,
                            ColumnNumber = 10,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 81,
                            CinemaId = 2,
                            ColumnNumber = 1,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 82,
                            CinemaId = 2,
                            ColumnNumber = 2,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 83,
                            CinemaId = 2,
                            ColumnNumber = 3,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 84,
                            CinemaId = 2,
                            ColumnNumber = 4,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 85,
                            CinemaId = 2,
                            ColumnNumber = 5,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 86,
                            CinemaId = 2,
                            ColumnNumber = 6,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 87,
                            CinemaId = 2,
                            ColumnNumber = 7,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 88,
                            CinemaId = 2,
                            ColumnNumber = 8,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 89,
                            CinemaId = 2,
                            ColumnNumber = 9,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 90,
                            CinemaId = 2,
                            ColumnNumber = 10,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 91,
                            CinemaId = 2,
                            ColumnNumber = 1,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 92,
                            CinemaId = 2,
                            ColumnNumber = 2,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 93,
                            CinemaId = 2,
                            ColumnNumber = 3,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 94,
                            CinemaId = 2,
                            ColumnNumber = 4,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 95,
                            CinemaId = 2,
                            ColumnNumber = 5,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 96,
                            CinemaId = 2,
                            ColumnNumber = 6,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 97,
                            CinemaId = 2,
                            ColumnNumber = 7,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 98,
                            CinemaId = 2,
                            ColumnNumber = 8,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 99,
                            CinemaId = 2,
                            ColumnNumber = 9,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 100,
                            CinemaId = 2,
                            ColumnNumber = 10,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 101,
                            CinemaId = 3,
                            ColumnNumber = 1,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 102,
                            CinemaId = 3,
                            ColumnNumber = 2,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 103,
                            CinemaId = 3,
                            ColumnNumber = 3,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 104,
                            CinemaId = 3,
                            ColumnNumber = 4,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 105,
                            CinemaId = 3,
                            ColumnNumber = 5,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 106,
                            CinemaId = 3,
                            ColumnNumber = 6,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 107,
                            CinemaId = 3,
                            ColumnNumber = 7,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 108,
                            CinemaId = 3,
                            ColumnNumber = 8,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 109,
                            CinemaId = 3,
                            ColumnNumber = 9,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 110,
                            CinemaId = 3,
                            ColumnNumber = 10,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 111,
                            CinemaId = 3,
                            ColumnNumber = 1,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 112,
                            CinemaId = 3,
                            ColumnNumber = 2,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 113,
                            CinemaId = 3,
                            ColumnNumber = 3,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 114,
                            CinemaId = 3,
                            ColumnNumber = 4,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 115,
                            CinemaId = 3,
                            ColumnNumber = 5,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 116,
                            CinemaId = 3,
                            ColumnNumber = 6,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 117,
                            CinemaId = 3,
                            ColumnNumber = 7,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 118,
                            CinemaId = 3,
                            ColumnNumber = 8,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 119,
                            CinemaId = 3,
                            ColumnNumber = 9,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 120,
                            CinemaId = 3,
                            ColumnNumber = 10,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 121,
                            CinemaId = 3,
                            ColumnNumber = 1,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 122,
                            CinemaId = 3,
                            ColumnNumber = 2,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 123,
                            CinemaId = 3,
                            ColumnNumber = 3,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 124,
                            CinemaId = 3,
                            ColumnNumber = 4,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 125,
                            CinemaId = 3,
                            ColumnNumber = 5,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 126,
                            CinemaId = 3,
                            ColumnNumber = 6,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 127,
                            CinemaId = 3,
                            ColumnNumber = 7,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 128,
                            CinemaId = 3,
                            ColumnNumber = 8,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 129,
                            CinemaId = 3,
                            ColumnNumber = 9,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 130,
                            CinemaId = 3,
                            ColumnNumber = 10,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 131,
                            CinemaId = 3,
                            ColumnNumber = 1,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 132,
                            CinemaId = 3,
                            ColumnNumber = 2,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 133,
                            CinemaId = 3,
                            ColumnNumber = 3,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 134,
                            CinemaId = 3,
                            ColumnNumber = 4,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 135,
                            CinemaId = 3,
                            ColumnNumber = 5,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 136,
                            CinemaId = 3,
                            ColumnNumber = 6,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 137,
                            CinemaId = 3,
                            ColumnNumber = 7,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 138,
                            CinemaId = 3,
                            ColumnNumber = 8,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 139,
                            CinemaId = 3,
                            ColumnNumber = 9,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 140,
                            CinemaId = 3,
                            ColumnNumber = 10,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 141,
                            CinemaId = 3,
                            ColumnNumber = 1,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 142,
                            CinemaId = 3,
                            ColumnNumber = 2,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 143,
                            CinemaId = 3,
                            ColumnNumber = 3,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 144,
                            CinemaId = 3,
                            ColumnNumber = 4,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 145,
                            CinemaId = 3,
                            ColumnNumber = 5,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 146,
                            CinemaId = 3,
                            ColumnNumber = 6,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 147,
                            CinemaId = 3,
                            ColumnNumber = 7,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 148,
                            CinemaId = 3,
                            ColumnNumber = 8,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 149,
                            CinemaId = 3,
                            ColumnNumber = 9,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 150,
                            CinemaId = 3,
                            ColumnNumber = 10,
                            RowNumber = 5
                        });
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            MovieId = 1,
                            StartTime = new DateTime(2024, 5, 20, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            MovieId = 1,
                            StartTime = new DateTime(2024, 5, 20, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            MovieId = 2,
                            StartTime = new DateTime(2024, 5, 21, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 2,
                            MovieId = 3,
                            StartTime = new DateTime(2024, 5, 21, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 3,
                            MovieId = 4,
                            StartTime = new DateTime(2024, 5, 21, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CinemaCity.Data.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 16.5,
                            Type = "Adult"
                        },
                        new
                        {
                            Id = 2,
                            Price = 13.0,
                            Type = "Child or student"
                        },
                        new
                        {
                            Id = 3,
                            Price = 13.0,
                            Type = "Elderly"
                        },
                        new
                        {
                            Id = 4,
                            Price = 13.0,
                            Type = "Disabled"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Booking", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.Showtime", "Showtime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaCity.Data.Models.ApplicationUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.BookingSeat", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaCity.Data.Models.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaCity.Data.Models.TicketType", null)
                        .WithMany("BookingSeats")
                        .HasForeignKey("TicketTypeId");

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.BookingTicket", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaCity.Data.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Movie", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Seat", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.Cinema", "Cinema")
                        .WithMany("Seats")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Showtime", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.Cinema", "Cinema")
                        .WithMany("Showtimes")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaCity.Data.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaCity.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CinemaCity.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaCity.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Booking", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Cinema", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Seat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.Showtime", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CinemaCity.Data.Models.TicketType", b =>
                {
                    b.Navigation("BookingSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
